#! /bin/sh

# Monitors config
bspc monitor DP-2 -d 1 2 3 4
bspc monitor HDMI-0 -d 5 6 7 8

# Bspwm config
bspc config border_width         2
bspc config window_gap           4
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config focused_border_color '#2DBDBD'
bspc config normal_border_color '#1e1e28'

# Autostart
xsetroot -cursor_name left_ptr
sxhkd &
picom -b &
flameshot &
dunst &
lxpolkit &
polybar top &
polybar top-second &
feh --bg-fill --randomize ~/wallpaper/*
